version: '3.8'
services:
  proposal-generator:
    build: .
    container_name: proposal-generator
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/custom_products.json:/app/backend/custom_products.json
      - ./backend/saved_draft.json:/app/backend/saved_draft.json
